import Head from "next/head";
import Link from "next/link";

import colors from "../data/colors.json";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Colors!</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			{colors.map((color) => (
				<Link key={color.name} href={`/${color.name}`} passHref>
					<h2>{color.name}</h2>
				</Link>
			))}
		</div>
	);
}
